name: NICK CARO PHOTOGRPAHY
favicon: null
layout_spectrum: 0.9609673847444355
typography_spectrum: 0.595442020567134
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.532312324270606
  lightness: 0.9361137668602169
  saturation: 0.7129389441106468
  rhythmicContrast: 0.7478736187331378
purpose: []
